(library
 (name test_ripe)
 (libraries ripe str)
 (inline_tests)
 (preprocess
  (pps ppx_expect ppx_inline_test))
 (modules
  span_utils
  diag
  dump
  pipeline
  test_lexer
  test_parser
  test_typecheck
  test_codegen
  test_source_map
  test_diagnostic
  test_symbol
  test_resolve
  test_error
  test_mangle
  test_config
  test_mir
  test_x86))
