(library
 (name ripe)
 (modules
  config
  span
  ast
  source_map
  diagnostic
  error
  tokens
  lexer
  bracket_check
  parser
  types
  symbol
  resolve
  ty_pred
  escape
  reachability
  typechecker
  typed_ast
  core
  const_eval
  const_fold
  lower
  codegen_qbe
  ripe_sites
  driver
  program)
 (libraries unix dune-site)
 (preprocess
  (pps ppx_deriving.show)))

(env
 (_
  (flags
   (:standard -w +a-4-42-70 -warn-error +a-4-30-40-42-70))))

(generate_sites_module
 (module ripe_sites)
 (sites ripe))

(ocamllex
 (modules lexer))
