(library
 (name ripe)
 (modules
  config
  span
  ast
  source_map
  diagnostic
  error
  tokens
  lexer
  parser
  types
  symbol
  resolve
  ty_pred
  escape
  reachability
  typechecker
  typed_ast
  core
  const_eval
  const_fold
  lower
  codegen_qbe
  ripe_sites
  driver)
 (libraries unix dune-site)
 (preprocess
  (pps ppx_deriving.show)))

(generate_sites_module
 (module ripe_sites)
 (sites ripe))

(ocamllex
 (modules lexer))
