(library
 (name ripe)
 (modules
  platform
  config
  target
  span
  interner
  nonempty
  ast
  source_map
  diagnostic
  tokens
  lexer
  bracket_check
  parser
  symbol
  program
  qname
  mangle
  types
  resolve
  ty_pred
  reachability
  sema
  typed_ast
  mir
  mir_verify
  mir_dump
  mir_build
  constant
  codegen_qbe
  x86_ir
  x86_encode
  elf64
  codegen_x86
  ripe_sites
  panic_table
  driver)
 (libraries unix dune-site)
 (preprocess
  (pps ppx_deriving.show)))

(env
 (_
  (flags
   (:standard -w +a-4-42-70 -warn-error +a-4-30-42-70))))

(generate_sites_module
 (module ripe_sites)
 (sites ripe))

(ocamllex
 (modules lexer))
