name: CI

on:
  pull_request:
    branches: [main]

jobs:
  compile:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/ci:latest
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      env:
        OPAMROOT: /home/opam/.opam
        OPAMROOTISOK: "1"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            code:
              - 'bin/**'
              - 'lib/**'
              - 'test/**'
              - 'dune-project'
              - 'ripe.opam'
              - 'ripe.opam.locked'
              - 'vendor/**'
      - if: steps.filter.outputs.code == 'true'
        run: opam install . --deps-only --locked --yes
      - if: steps.filter.outputs.code == 'true'
        run: opam exec -- dune build
      - if: steps.filter.outputs.code == 'true'
        run: opam exec -- dune build @fmt
      - if: steps.filter.outputs.code == 'true'
        run: make -C vendor/qbe
      - if: steps.filter.outputs.code == 'true'
        run: opam exec -- dune runtest
        env:
          QBE: ${{ github.workspace }}/vendor/qbe/obj/qbe

  build:
    runs-on: ubuntu-latest
    needs: [compile]
    if: always()
    steps:
      - run: exit ${{ contains(needs.*.result, 'failure') && 1 || 0 }}
