name: CI

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "**.txt"
      - ".gitignore"
      - "LICENSE-MIT"
      - "LICENSE-GPL"
      - ".editorconfig"
      - "docs/**"
      - "examples/**"
      - "todo/**"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/ci:latest
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      env:
        OPAMROOT: /home/opam/.opam
        OPAMROOTISOK: "1"
    defaults:
      run:
        working-directory: compiler
    steps:
      - uses: actions/checkout@v4
      - run: opam install . --deps-only --locked --yes
      - run: opam exec -- dune build
      - run: opam exec -- dune build @fmt
      - run: opam exec -- dune runtest

  ci:
    runs-on: ubuntu-latest
    needs: [build]
    if: always()
    steps:
      - run: exit ${{ contains(needs.*.result, 'failure') && 1 || 0 }}
